import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import copy from 'esbuild-plugin-copy';
import {sassPlugin} from 'esbuild-sass-plugin';


const staticAssetsPlugin = {
    name: 'static-assets-plugin',
    setup(build) {
        build.onLoad({ filter: /.+/ }, (args) => {
            return {
                watchFiles: ['styles.css', 'src/scss/layout.scss'],
            };
        });
    },
};


const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const TEST_VAULT = 'test-vault/.obsidian/plugins/obsidian-advanced-slides';

esbuild.build({
        banner: {
            js: banner,
        },
        entryPoints: ['src/main.ts'],
        bundle: true,
        external: ['obsidian', 'electron', ...builtins],
        format: 'cjs',
        watch: !prod,
        target: 'es2020',
        logLevel: "info",
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
        outfile: TEST_VAULT + '/main.js',
        plugins: [
            staticAssetsPlugin,
            copy.default({
                assets: {
                    from: ['manifest.json', 'styles.css', 'distVersion.json'],
                    to: ['.'],
                }
            }),
            copy.default({
                assets: {
                    from: ['src/template/*'],
                    to: ['./template/'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/dist/*'],
                    to: ['./dist'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/dist/theme/*'],
                    to: ['./dist/theme'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/dist/theme/fonts/league-gothic/*'],
                    to: ['./dist/theme/fonts/league-gothic'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/dist/theme/fonts/source-sans-pro/*'],
                    to: ['./dist/theme/fonts/source-sans-pro'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/highlight/*'],
                    to: ['./plugin/highlight'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/markdown/*'],
                    to: ['./plugin/markdown'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/math/*'],
                    to: ['./plugin/math'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/notes/*'],
                    to: ['./plugin/notes'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/search/*'],
                    to: ['./plugin/search'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/reveal.js/plugin/zoom/*'],
                    to: ['./plugin/zoom'],
                }
            }),
			copy.default({
                assets: {
                    from: ['node_modules/reveal.js-mermaid-plugin/plugin/mermaid/*'],
                    to: ['./plugin/mermaid'],
                }
            }),
            copy.default({
                assets: {
                    from: ['node_modules/highlight.js/styles/vs2015.css'],
                    to: ['./css'],
                }
            }),
            copy.default({
                assets: {
                    from: ['src/css/mattropolis.css'],
                    to: ['./css'],
                }
            }),
            copy.default({
                assets: prod ? {} : {
                    from: ['.hotreload'],
                    to: ['.'],
                },
            }),
        ],
    }).then(esbuild.build({
        entryPoints: [
            'src/scss/layout.scss',
        ],
        loader: {
            '.eot': 'dataurl',
            '.woff': 'dataurl',
            '.ttf': 'dataurl',
            '.svg': 'dataurl',
            '.otf': 'dataurl'
        },
        outfile: TEST_VAULT + '/css/layout.css',
		bundle: true,
        external: ['obsidian', 'electron', ...builtins],
        watch: !prod,
        target: 'es2020',
        logLevel: "info",
        sourcemap: prod ? false : 'inline',
        treeShaking: true,
		plugins: [
			sassPlugin({
			  implementation: 'node-sass',
			}),
		  ]
    }))
    .catch(() => process.exit(1));
