export type Options = {
	theme: string;
	highlightTheme: string;
	template: string;
	separator: string;
	verticalSeparator: string;
	notesSeparator: string;
	enableLinks: boolean;
	title: string;
	css: string | string[];
	remoteCSS: string | string[];
	width: number;
	height: number;
	margin: number;
	showGrid: boolean;
	bg: string;
	center: boolean;
	log: boolean;
	defaultTemplate: string;
};
